// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vfegxeoihucdjdnilzdo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZmZWd4ZW9paHVjZGpkbmlsemRvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI5MDM3MTQsImV4cCI6MjA4ODQ3OTcxNH0.HMg-oAJ3GDdrjXcfBH4kS7MBlb27z3ApvZYPC-yvCUo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});